name: Main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22
      - run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
